# Generated by Django 5.1.3 on 2025-02-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hi', '0004_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='heading',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
