# Generated by Django 5.1.3 on 2025-02-04 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hi', '0005_services_heading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='heading',
        ),
    ]
