# Generated by Django 5.1.3 on 2025-02-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hi', '0006_remove_services_heading'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200, null=True)),
                ('img1', models.FileField(blank=True, default=True, null=True, upload_to='')),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
