# Generated by Django 5.1.3 on 2025-02-04 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hi', '0007_heading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heading',
            name='heading',
        ),
    ]
