# Generated by Django 5.1.3 on 2025-02-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hi', '0008_remove_heading_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='heading',
            name='heading',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
