# Generated by Django 5.1.3 on 2025-02-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hi', '0009_heading_heading'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='img1',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='services',
            name='heading',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
