# Generated by Django 5.1.3 on 2025-02-04 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hi', '0010_rename_img1_services_image1_services_heading'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='heading',
            new_name='headingg',
        ),
    ]
