# Generated by Django 5.1.3 on 2025-02-04 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hi', '0011_rename_heading_services_headingg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heading',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='services',
            name='headingg',
        ),
    ]
