# Generated by Django 5.1.3 on 2025-02-04 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hi', '0012_remove_heading_heading_remove_services_headingg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Heading',
            new_name='Service',
        ),
    ]
