# Generated by Django 5.1.3 on 2025-02-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hi', '0013_rename_heading_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AddField(
            model_name='services',
            name='href',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
