# Generated by Django 5.1.3 on 2025-02-22 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hi', '0015_cake'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='food',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cake', to='hi.cart'),
        ),
    ]
