# Generated by Django 5.1.3 on 2025-02-23 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hi', '0016_remove_cartitem_food_alter_cartitem_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cake',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food', to='hi.category'),
        ),
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.FileField(blank=True, default=True, null=True, upload_to='food'),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
