# Generated by Django 5.1.3 on 2025-02-23 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hi', '0017_delete_cake_remove_cartitem_cart_alter_food_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food',
        ),
    ]
