# Generated by Django 5.1.3 on 2025-02-23 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hi', '0019_cart_food_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product',
            new_name='food',
        ),
    ]
