# Generated by Django 5.1.3 on 2025-03-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hi', '0021_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='C_oder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('about', models.TextField(null=True)),
                ('price', models.IntegerField(max_length=50)),
            ],
        ),
    ]
