# Generated by Django 5.1.3 on 2025-03-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hi', '0022_c_oder'),
    ]

    operations = [
        migrations.AddField(
            model_name='c_oder',
            name='image',
            field=models.FileField(blank=True, default=True, null=True, upload_to=''),
        ),
    ]
