# Generated by Django 5.1.3 on 2025-03-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hi', '0023_c_oder_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='c_oder',
            name='href',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
