# Generated by Django 5.1.3 on 2025-03-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hi', '0024_c_oder_href'),
    ]

    operations = [
        migrations.CreateModel(
            name='S_oder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, default=True, null=True, upload_to='')),
                ('name', models.CharField(max_length=100, null=True)),
                ('about', models.TextField(null=True)),
                ('price', models.IntegerField(max_length=20)),
                ('href', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
